model: ["xxsmall"]
seq_len: [8192]
batch_size: [1]
steps: [120000]
unlimited_steps: [False]
dump_freq: [100]

# model.modalities.image.encoder_name: ["llama4_flash_encoder"]
# model.modalities.image.vision_encoder_ckpt_path: ["/mnt/wsfuse/nextgen_mm/vision_encoders/llama4_flash_encoder_final_1023_ema"]

model.modalities.image.encoder_name: ["llama4_flash_encoder_vev0p3_336"]
model.modalities.image.vision_encoder_ckpt_path: ["/mnt/wsfuse/tranx/vision_encoders/llama4_flash_vit_g14_336_fair_vev0p3_epoch_420"]

async_checkpointing: [True]
checkpoint.async_checkpointing_staging_method: ["async_copy_async_serialize"]
checkpoint.use_checkpointing_process: [True]
dump_dir_tree_type: ["sharded"]
checkpoint.use_checkpoint_barrier_wait_for_all_files: [True]
checkpoint.checkpoint_barrier_type: ["sc"]
checkpoint.dump_freq_ephemeral: [-1]
checkpoint.checkpoint_gc_use_rmdir: [True]

dataloader.image.patch_width: [14]
dataloader.image.patch_height: [14]
dataloader.image.image_width: [336]
dataloader.image.image_height: [336]
dataloader.image.use_pixel_shuffle: [True]
dataloader.image.ps_ratio: [0.5]
dataloader.image.use_dynamic_transform: [True]
dataloader.image.max_num_chunks: [9]
dataloader.image.use_tile_separator_tags: [True]
dataloader.video.num_frames_per_video: [8]
model.modalities.use_image: [True]
model.freeze_vision_encoder: [True]
model.modalities.image.freeze_vision_encoder: [False]
model.modalities.image.recompute_transformer: [True]
model.modalities.image.vision_adapter_type: ["pixel_shuffle_mlp"]
model.modalities.image.ps_ratio: [0.5]
model.modalities.image.use_dynamic_transform: [True]

model.modalities.image.patch_width: [14]
model.modalities.image.patch_height: [14]
model.modalities.image.image_width: [336]
model.modalities.image.image_height: [336]
model.modalities.image.enable_projection: [True]
model.modalities.image.use_cached_embeddings: [False]
model.modalities.use_video: [True]

# eager_init: [False]
# dump_dir: [$DUMP_DIR]
enable_ods: [True]
periodic_gpu_check: [False]
gpu_check_level: [-1]

model.efficient_attn: ["auto"]
model.attn_bias_type: ["block_causal"]
model.non_linearity: ["swiglu"]
model.use_rope: [True]
model.recompute_fc1_out: [True]
model.recompute_fc3_out: [True]
model.recompute_attn: [False]
model.custom_bwd: [False]
model.layer_ckpt: [none]
model.vocab_parallel: [True]
model.rope_theta: [500000.0]
model.rope_use_fp32_in_outer_product: [True]
model.lc_rope_len: [131072]
model.lc_rope_prob: [0.1]
model.use_scaled_rope: [True]
model.rope_scale_factor: [8]
model.high_freq_factor: [1]
model.use_qk_norm: [True]
model.qk_norm_across_heads: [False]
model.sequence_parallel: [True]
model.enable_fsdpv2: [True]
model.te_use_fsdp_mixed_precision: [True]
model.use_te_layers: [True]
model.init.use_gaussian: [True]
model.init.use_depth: ["current"]
model.alpha_depth: ["disabled"]
model.init.depth_last: [False]

# parallelism
model_parallel_size: [2]
expert_parallel_size: [2]

fp32_reduce_scatter: ["all"]
reshard_after_forward: [True]
overlap_p2p_communication: [True]
batch_p2p_communication: [False]
num_microbatches_with_partial_activation_checkpoints: [1]
mb_recompute_attn: [False]
mb_recompute_fc1_fc3: [True]

# optim
optim.lr: [4e-3]
optim.lr_min_ratio: [0.01]
optim.warmup: [8000]
optim.use_fp32_copy_optim: [True]
optim.clip: [1.0]
optim.epsilon: [1e-12]
optim.modality_order: ["text,vision,speech"]
optim.independent_weight_decay: [False]
optim.weight_decay: [0.0125]

eval_freq: [1000]
keep_eval_checkpoints: [True]
skip_evals_during_training: [True]
log_freq: [1]
log_all_steps: [True]
log_batch_checksum: [True]
log.log_scalars: [True]
log.reduce_scalars: [True]
enable_loss_tracker: [True]

runtime_nccl_timeout_s: [600]
gc_collect_freq: [1000]
profile_freq: [-1]
dump_profile_traces: [True]
profile_record_shapes: [True]
enable_pynvml: [False]
tokenizer: ["l4_202k_tok"]
tokenizer.directory: ["/mnt/wsfuse/tokenizers/tiktoken"]
iter_type: ["text_airstore"]
iter_text_airstore.dataloader_workers_per_gpu: [4]
iter_text_airstore.prefetch_factor: [20]
iter_text_airstore.max_world_size: [96]
iter_text_airstore.simulate_training_budget: [30000000000000]
data: ["llama4_flash_encoder_midtrain_0000_cc_image_synthetic_interleave_llama3v_captions_no_user_data"]

model.init.truncate_std_mult: [2]
model.init.router_coeff_std: [0.1]
model.experts_choice_moe.use_te_in_moe: [True]
model.multiple_of: [2048]
model.experts_choice_moe.is_enabled: [True]
model.experts_choice_moe.sharding_strategy: ["dp2ep-v1"]
model.experts_choice_moe.overlap_token_comm: [True]
model.experts_choice_moe.sigmoid_in_fp32: [True]
model.experts_choice_moe.input_scaling: [False]
model.experts_choice_moe.running_stats_ema: [0.99]
model.experts_choice_moe.eval_with_saved_stats: [True]
model.experts_choice_moe.expert_activation_model: [True]
model.experts_choice_moe.shuffle_before_assign: [True]
model.experts_choice_moe.skip_local_shuffle: [False]
model.experts_choice_moe.shuffle_with_random_order: [True]
model.experts_choice_moe.shuffle_group_size: [4]
model.experts_choice_moe.num_experts: [2]


model.metap.use_metap: [True]
model.metap.metap_mode: ["ntp"]
model.metap.base_width: [256]
model.metap.coeff_std: [1.0]
model.metap.m_emb: [1.0]
model.metap.tie_router_bulk_coeff_std: [False]
checkpoint.eager_init_staging_buffer: [False]
text_only_steps: [80000]

aggregate_gradients_by_tokens: [True]
